<script>
    // @ts-nocheck
    import { createEventDispatcher } from 'svelte';
    const dispatch = createEventDispatcher();
    
    export let selectedItem;
    let name = "";
    import sizingSmall from "$lib/assets/sizingSmall.png";
    import sizingMedium from "$lib/assets/sizingMedium.png";
    import sizingLarge from "$lib/assets/sizingLarge.png";

    const selectItem = (e) => {
        let el = e.target;
        dispatch('selectItem', {el: el});
    }

    const selectSize = (e) =>{
        let el = e.target;
        dispatch('selectSize', {el: el});
    }

    const nameInput = ()=>{
        dispatch('nameInput', name);
    }


</script>

<h2 class="mt-8 text-lg font-medium flex items-center gap-2">Final step, choose an item to display your pet
    <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="w-5 h-5 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button>
    <div data-popover id="popover-description" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
        <div class="p-3 space-y-2">
            <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
            <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
            <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
            <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
            <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg></a>
        </div>
        <div data-popper-arrow></div>
    </div> 
</h2>

<p class="text-sm text-gray-500">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, dolorem inventore! Culpa ist.</p>

<div class="mt-6 w-full flex flex-wrap gap-y-8 gap-x-11">
    <div on:click={selectItem}>
        <img class="mb-2 box-size rounded-xl shadow-sm border border-gray-400 object-cover" src="https://images.loox.io/uploads/2024/1/17/eIxaVNs1Hb.jpg" alt="">
        <p class="text-lg text-center font-medium">Poster</p>
    </div>

    <div on:click={selectItem}>
        <img class="mb-2 box-size rounded-xl shadow-sm border border-gray-400 object-cover" src="https://cuddleclones.com/cdn/shop/files/pinkpaws-1_19_1200x.png?v=1690806529" alt="">
        <p class="text-lg text-center font-medium">Blanket</p>
    </div>

    <div on:click={selectItem}>
        <img class="mb-2 box-size rounded-xl shadow-sm border border-gray-400 object-cover" src="https://cuddleclones.com/cdn/shop/files/pinkpaws-1_24_1200x.png?v=1690806744" alt="">
        <p class="text-lg text-center font-medium">Ceramic Mug</p>
    </div>
</div>

{#if selectedItem === "Poster"}
    <div>
        <p class="mt-6 text-lg font-medium flex items-center gap-2">What size would you like for ya poster?</p>
        <div class="mt-4 w-full flex flex-wrap gap-y-8 gap-x-11">
            <div on:click={selectSize}>
                <img class="mb-2 h-32 w-32 rounded-xl shadow-sm border border-gray-400 object-cover" src={sizingSmall} alt="">
                <p class="text-center font-medium">Medium 16"x24"</p>
            </div>

            <div on:click={selectSize}>
                <img class="mb-2 h-32 w-32 rounded-xl shadow-sm border border-gray-400 object-cover" src={sizingMedium} alt="">
                <p class="text-center font-medium">Large 20"x30"</p>
            </div>

            <div on:click={selectSize}>
                <img class="mb-2 h-32 w-32 rounded-xl shadow-sm border border-gray-400 object-cover" src={sizingLarge} alt="">
                <p class="text-center font-medium">Huge 24"x36"</p>
            </div>
        </div>
    </div>
    {:else if selectedItem === "Blanket"}
    <div>
        <p class="mt-6 text-lg font-medium flex items-center gap-2">What size would you like fo ya blanket?</p>
        <div class="mt-4 w-full flex flex-wrap gap-y-8 gap-x-11">
            <div on:click={selectSize}>
                <img class="mb-2 h-32 w-32 rounded-xl shadow-sm border border-gray-400 object-cover" src={sizingSmall} alt="">
                <p class="text-center font-medium">Medium 16"x24"</p>
            </div>

            <div on:click={selectSize}>
                <img class="mb-2 h-32 w-32 rounded-xl shadow-sm border border-gray-400 object-cover" src={sizingMedium} alt="">
                <p class="text-center font-medium">Large 20"x30"</p>
            </div>

            <div on:click={selectSize}>
                <img class="mb-2 h-32 w-32 rounded-xl shadow-sm border border-gray-400 object-cover" src={sizingLarge} alt="">
                <p class="text-center font-medium">Huge 24"x36"</p>
            </div>
        </div>
    </div>
{/if}

<div class="mt-8 mb-12">
    <label for="first_name" class="block mb-2 font-medium text-gray-900">What's a good name for lil bro?</label>
    <input bind:value={name} on:input={nameInput} type="text" id="first_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" placeholder="John" required>
</div>