<script>
    // @ts-nocheck
    import { tweened } from "svelte/motion";
    import { onDestroy } from "svelte";
    import { createEventDispatcher } from 'svelte';

    export let petPhotos;
    let uploadingImage = false;
    let uploadProgress = tweened(0);
    let intervalId;

    const dispatch = createEventDispatcher();

    function uploadPhoto(e) {
        intervalId = setInterval(() => {
            $uploadProgress += 5;
            if($uploadProgress >= 100){ 
                uploadProgress.set(0)
            }
        }, 500);

        uploadingImage = true;

        let el = e.target;
        dispatch('uploadPhoto', {el: el});

        uploadingImage = false;
    }

    onDestroy(() => {
        clearInterval(intervalId);
    });
</script>

<h2 class="mt-8 text-lg font-medium flex items-center gap-2">Next, upload a few clear photos of your pet 
    <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="w-5 h-5 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button>
    <div data-popover id="popover-description" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
        <div class="p-3 space-y-2">
            <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
            <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
            <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
            <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
            <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg></a>
        </div>
        <div data-popper-arrow></div>
    </div>
</h2>


<h2 class="mt-6 mb-2 font-medium text-gray-900 dark:text-white">For the best results:</h2>
<ul class="text-sm max-w-md space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
    <li>
        Make sure your pet’s face is clearly visible
    </li>
    <li>
        Upload a few photos of your pet from different angles
    </li>
    <li>
        Don’t stress - if the photos aren’t suitable we’ll reach to help. 
    </li>
</ul>


<div class="mt-8 flex items-center justify-center w-full">
    <label for="dropzone-file" class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 hover:bg-gray-100"> 
        <div class="flex flex-col items-center justify-center pt-5 pb-6"> <svg class="w-8 h-8 mb-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16"> 
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/> 
        </svg> 
        <p class="mb-2 text-sm text-gray-500">
            <span class="font-semibold">Click to upload</span></p> 
            <p class="text-xs text-gray-500">SVG, PNG, JPG or GIF (MAX. 800x400px)</p> 

            <div class="{!uploadingImage ? "hidden" : ""} mt-5 w-full bg-gray-200 rounded-full h-1.5 mb-4 dark:bg-gray-700">
                <div class="bg-blue-600 h-1.5 rounded-full dark:bg-blue-500 transition-all" style="width: {$uploadProgress }%;"></div>
            </div>
        </div> 
        <input id="dropzone-file" type="file" on:change={uploadPhoto} class="hidden" /> 
    </label> 
</div>

<div class="mt-6 flex flex-col gap-4">
    {#each petPhotos as file}
        <div class="w-full bg-white py-2 px-4 rounded-md border border-gray-300 flex justify-between items-center">
            <div class="flex items-center gap-3">
                <img class="w-8 p-1.5 bg-blue-100 rounded-md" src="https://img.icons8.com/material-rounded/100/2563EB/image.png" alt="">
                <p class="text-sm">{file.name.length > 10 ? `${file.name.slice(0,8)}... ${file.name.slice(file.name.lastIndexOf(".") + 1)}` : ""}</p>
            </div>
            <img class="h-6" src="https://img.icons8.com/ios-filled/50/multiply.png" alt="">
        </div>
    {/each}
</div>